name: DropControl
main: oxy.dropcontrol.Main
version: 1.1
description: Controlez les drops
author: Oxygened
commands:
    dropcontrol:
      description: Affiche l'aide
      usage: /dropcontrol
      permission: dropcontrol.admin
      permission-message: You don't have <permission>
    dropcontrol manager:
      description: Ouvre le world manager
      usage: /dropcontrol manager [world]
      permission: dropcontrol.admin
      permission-message: You don't have <permission>
    dropcontrol reload:
      description: Recharge la configuration
      usage: /dropcontrol reload
      permission: dropcontrol.admin
      permission-message: You don't have <permission>